/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sol.petroleum.master.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the inventory service. Represents a row in the &quot;sol_master_data_inventory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sol.petroleum.master.data.model.impl.inventoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sol.petroleum.master.data.model.impl.inventoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see inventory
 * @generated
 */
@ProviderType
public interface inventoryModel extends BaseModel<inventory>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a inventory model instance should use the {@link inventory} interface instead.
	 */

	/**
	 * Returns the primary key of this inventory.
	 *
	 * @return the primary key of this inventory
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this inventory.
	 *
	 * @param primaryKey the primary key of this inventory
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the master data inventory ID of this inventory.
	 *
	 * @return the master data inventory ID of this inventory
	 */
	public long getMasterDataInventoryId();

	/**
	 * Sets the master data inventory ID of this inventory.
	 *
	 * @param masterDataInventoryId the master data inventory ID of this inventory
	 */
	public void setMasterDataInventoryId(long masterDataInventoryId);

	/**
	 * Returns the item number of this inventory.
	 *
	 * @return the item number of this inventory
	 */
	@AutoEscape
	public String getItemNumber();

	/**
	 * Sets the item number of this inventory.
	 *
	 * @param itemNumber the item number of this inventory
	 */
	public void setItemNumber(String itemNumber);

	/**
	 * Returns the company ID of this inventory.
	 *
	 * @return the company ID of this inventory
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this inventory.
	 *
	 * @param companyId the company ID of this inventory
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the inter ID of this inventory.
	 *
	 * @return the inter ID of this inventory
	 */
	@AutoEscape
	public String getInterId();

	/**
	 * Sets the inter ID of this inventory.
	 *
	 * @param interId the inter ID of this inventory
	 */
	public void setInterId(String interId);

	/**
	 * Returns the location code of this inventory.
	 *
	 * @return the location code of this inventory
	 */
	@AutoEscape
	public String getLocationCode();

	/**
	 * Sets the location code of this inventory.
	 *
	 * @param locationCode the location code of this inventory
	 */
	public void setLocationCode(String locationCode);

	/**
	 * Returns the location desc of this inventory.
	 *
	 * @return the location desc of this inventory
	 */
	@AutoEscape
	public String getLocationDesc();

	/**
	 * Sets the location desc of this inventory.
	 *
	 * @param locationDesc the location desc of this inventory
	 */
	public void setLocationDesc(String locationDesc);

	/**
	 * Returns the qty on order of this inventory.
	 *
	 * @return the qty on order of this inventory
	 */
	public Integer getQtyOnOrder();

	/**
	 * Sets the qty on order of this inventory.
	 *
	 * @param qtyOnOrder the qty on order of this inventory
	 */
	public void setQtyOnOrder(Integer qtyOnOrder);

	/**
	 * Returns the qty back ordered of this inventory.
	 *
	 * @return the qty back ordered of this inventory
	 */
	public Integer getQtyBackOrdered();

	/**
	 * Sets the qty back ordered of this inventory.
	 *
	 * @param qtyBackOrdered the qty back ordered of this inventory
	 */
	public void setQtyBackOrdered(Integer qtyBackOrdered);

	/**
	 * Returns the qty drop shipped of this inventory.
	 *
	 * @return the qty drop shipped of this inventory
	 */
	public Integer getQtyDropShipped();

	/**
	 * Sets the qty drop shipped of this inventory.
	 *
	 * @param qtyDropShipped the qty drop shipped of this inventory
	 */
	public void setQtyDropShipped(Integer qtyDropShipped);

	/**
	 * Returns the qty in use of this inventory.
	 *
	 * @return the qty in use of this inventory
	 */
	public Integer getQtyInUse();

	/**
	 * Sets the qty in use of this inventory.
	 *
	 * @param qtyInUse the qty in use of this inventory
	 */
	public void setQtyInUse(Integer qtyInUse);

	/**
	 * Returns the qty in service of this inventory.
	 *
	 * @return the qty in service of this inventory
	 */
	public Integer getQtyInService();

	/**
	 * Sets the qty in service of this inventory.
	 *
	 * @param qtyInService the qty in service of this inventory
	 */
	public void setQtyInService(Integer qtyInService);

	/**
	 * Returns the qty returned of this inventory.
	 *
	 * @return the qty returned of this inventory
	 */
	public Integer getQtyReturned();

	/**
	 * Sets the qty returned of this inventory.
	 *
	 * @param qtyReturned the qty returned of this inventory
	 */
	public void setQtyReturned(Integer qtyReturned);

	/**
	 * Returns the qty damaged of this inventory.
	 *
	 * @return the qty damaged of this inventory
	 */
	public Integer getQtyDamaged();

	/**
	 * Sets the qty damaged of this inventory.
	 *
	 * @param qtyDamaged the qty damaged of this inventory
	 */
	public void setQtyDamaged(Integer qtyDamaged);

	/**
	 * Returns the qty on hand of this inventory.
	 *
	 * @return the qty on hand of this inventory
	 */
	public Integer getQtyOnHand();

	/**
	 * Sets the qty on hand of this inventory.
	 *
	 * @param qtyOnHand the qty on hand of this inventory
	 */
	public void setQtyOnHand(Integer qtyOnHand);

	/**
	 * Returns the qty allocated of this inventory.
	 *
	 * @return the qty allocated of this inventory
	 */
	public Integer getQtyAllocated();

	/**
	 * Sets the qty allocated of this inventory.
	 *
	 * @param qtyAllocated the qty allocated of this inventory
	 */
	public void setQtyAllocated(Integer qtyAllocated);

	/**
	 * Returns the qty committed of this inventory.
	 *
	 * @return the qty committed of this inventory
	 */
	public Integer getQtyCommitted();

	/**
	 * Sets the qty committed of this inventory.
	 *
	 * @param qtyCommitted the qty committed of this inventory
	 */
	public void setQtyCommitted(Integer qtyCommitted);

	/**
	 * Returns the qty sold of this inventory.
	 *
	 * @return the qty sold of this inventory
	 */
	public Integer getQtySold();

	/**
	 * Sets the qty sold of this inventory.
	 *
	 * @param qtySold the qty sold of this inventory
	 */
	public void setQtySold(Integer qtySold);

	/**
	 * Returns the inactive of this inventory.
	 *
	 * @return the inactive of this inventory
	 */
	public Integer getInactive();

	/**
	 * Sets the inactive of this inventory.
	 *
	 * @param inactive the inactive of this inventory
	 */
	public void setInactive(Integer inactive);

	/**
	 * Returns the created date of this inventory.
	 *
	 * @return the created date of this inventory
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this inventory.
	 *
	 * @param createdDate the created date of this inventory
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this inventory.
	 *
	 * @return the modified date of this inventory
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this inventory.
	 *
	 * @param modifiedDate the modified date of this inventory
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public inventory cloneWithOriginalValues();

}