/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sol.petroleum.master.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the item service. Represents a row in the &quot;sol_master_data_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sol.petroleum.master.data.model.impl.itemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sol.petroleum.master.data.model.impl.itemImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see item
 * @generated
 */
@ProviderType
public interface itemModel extends BaseModel<item> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item model instance should use the {@link item} interface instead.
	 */

	/**
	 * Returns the primary key of this item.
	 *
	 * @return the primary key of this item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item.
	 *
	 * @param primaryKey the primary key of this item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the master data item ID of this item.
	 *
	 * @return the master data item ID of this item
	 */
	public long getMasterDataItemId();

	/**
	 * Sets the master data item ID of this item.
	 *
	 * @param masterDataItemId the master data item ID of this item
	 */
	public void setMasterDataItemId(long masterDataItemId);

	/**
	 * Returns the category of this item.
	 *
	 * @return the category of this item
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this item.
	 *
	 * @param category the category of this item
	 */
	public void setCategory(String category);

	/**
	 * Returns the inactive of this item.
	 *
	 * @return the inactive of this item
	 */
	public Integer getInactive();

	/**
	 * Sets the inactive of this item.
	 *
	 * @param inactive the inactive of this item
	 */
	public void setInactive(Integer inactive);

	/**
	 * Returns the inter ID of this item.
	 *
	 * @return the inter ID of this item
	 */
	@AutoEscape
	public String getInterId();

	/**
	 * Sets the inter ID of this item.
	 *
	 * @param interId the inter ID of this item
	 */
	public void setInterId(String interId);

	/**
	 * Returns the item number of this item.
	 *
	 * @return the item number of this item
	 */
	@AutoEscape
	public String getItemNumber();

	/**
	 * Sets the item number of this item.
	 *
	 * @param itemNumber the item number of this item
	 */
	public void setItemNumber(String itemNumber);

	/**
	 * Returns the item tax sch ID of this item.
	 *
	 * @return the item tax sch ID of this item
	 */
	@AutoEscape
	public String getItemTaxSchId();

	/**
	 * Sets the item tax sch ID of this item.
	 *
	 * @param itemTaxSchId the item tax sch ID of this item
	 */
	public void setItemTaxSchId(String itemTaxSchId);

	/**
	 * Returns the item type of this item.
	 *
	 * @return the item type of this item
	 */
	public Integer getItemType();

	/**
	 * Sets the item type of this item.
	 *
	 * @param itemType the item type of this item
	 */
	public void setItemType(Integer itemType);

	/**
	 * Returns the sub category of this item.
	 *
	 * @return the sub category of this item
	 */
	@AutoEscape
	public String getSubCategory();

	/**
	 * Sets the sub category of this item.
	 *
	 * @param subCategory the sub category of this item
	 */
	public void setSubCategory(String subCategory);

	/**
	 * Returns the tax options of this item.
	 *
	 * @return the tax options of this item
	 */
	public Integer getTaxOptions();

	/**
	 * Sets the tax options of this item.
	 *
	 * @param taxOptions the tax options of this item
	 */
	public void setTaxOptions(Integer taxOptions);

	/**
	 * Returns the title of this item.
	 *
	 * @return the title of this item
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this item.
	 *
	 * @param title the title of this item
	 */
	public void setTitle(String title);

	/**
	 * Returns the u of m schedule of this item.
	 *
	 * @return the u of m schedule of this item
	 */
	@AutoEscape
	public String getUOfMSchedule();

	/**
	 * Sets the u of m schedule of this item.
	 *
	 * @param uOfMSchedule the u of m schedule of this item
	 */
	public void setUOfMSchedule(String uOfMSchedule);

	/**
	 * Returns the visibility of this item.
	 *
	 * @return the visibility of this item
	 */
	@AutoEscape
	public String getVisibility();

	/**
	 * Sets the visibility of this item.
	 *
	 * @param visibility the visibility of this item
	 */
	public void setVisibility(String visibility);

	/**
	 * Returns the created date of this item.
	 *
	 * @return the created date of this item
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this item.
	 *
	 * @param createdDate the created date of this item
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this item.
	 *
	 * @return the modified date of this item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this item.
	 *
	 * @param modifiedDate the modified date of this item
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public item cloneWithOriginalValues();

}